# [START cloudbuild_basic_config]

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Docker Build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-east1-docker.pkg.dev/mlops489-breastcancer/mlops489breastcancer/breastcancerstart-image:latest', '.']
images:
- 'us-east1-docker.pkg.dev/mlops489-breastcancer/mlops489breastcancer/breastcancerstart-image:latest'
# [END cloudbuild_basic_config]
