wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.11
    cli_version: 0.19.11
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747586817
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 14
      - 23
      - 37
      4: 3.11.11
      5: 0.19.11
      8:
      - 5
      13: darwin-arm64
C:
  desc: null
  value: 10
max_iter:
  desc: null
  value: 500
solver:
  desc: null
  value: lbfgs
